export const conditions = [
  'Diabetes',
  'Colesterol alto',
  'Hipertensión',
  'Obesidad',
  'Insuficiencia renal crónica',
  'Hipotiroidismo',
  'Hipertiroidismo',
  'Artritis reumatoide',
  'Osteoporosis',
  'Síndrome metabólico',
  'Anemia',
  'Gota',
  'Enfermedad del hígado graso no alcohólico (NAFLD)',
  'Apnea del sueño',
  'Intolerancia a la lactosa',
  'Enfermedad celíaca',
  'Triglicéridos elevados',
  'Enfermedad coronaria',
  'Arritmias cardíacas',
  'Insuficiencia cardíaca congestiva',
  'Asma',
  'EPOC (Enfermedad pulmonar obstructiva crónica)',
  'Depresión',
  'Ansiedad',
  'Enfermedad de Crohn',
  'Colitis ulcerosa',
  'Síndrome del intestino irritable (SII)',
  'Hipoglucemia',
  'Migrañas crónicas',
  'Dermatitis atópica',
  'Psoriasis'
];
